Add-WindowsCapability -Name 'IIS-WebServerRole' -Online
Add-WindowsCapability -Name 'IIS-WebServer' -Online
Add-WindowsCapability -Name 'IIS-CommonHttpFeatures' -Online
Add-WindowsCapability -Name 'IIS-HttpErrors' -Online
Add-WindowsCapability -Name 'IIS-HttpRedirect' -Online
Add-WindowsCapability -Name 'IIS-ApplicationDevelopment' -Online
Add-WindowsCapability -Name 'IIS-ASPNET' -Online
Add-WindowsCapability -Name 'IIS-NetFxExtensibility' -Online
Add-WindowsCapability -Name 'IIS-ASPNET45' -Online
Add-WindowsCapability -Name 'IIS-WebServerManagementTools' -Online
Add-WindowsCapability -Name 'IIS-ManagementConsole' -Online
Add-WindowsCapability -Name 'IIS-ManagementScriptingTools' -Online
Add-WindowsCapability -Name 'IIS-ManagementService' -Online
Add-WindowsCapability -Name 'IIS-IIS6ManagementCompatibility' -Online
Add-WindowsCapability -Name 'IIS-Metabase' -Online
Add-WindowsCapability -Name 'IIS-WMICompatibility' -Online
Add-WindowsCapability -Name 'IIS-LegacyScripts' -Online
Add-WindowsCapability -Name 'IIS-LegacySnapIn' -Online

